// Do not edit: this file is generated by scripts/generate-icons,
// changes will be overwritten.
export { default as IconCog } from './IconCog'
export { default as IconCopy } from './IconCopy'
export { default as IconCross} from './IconCross'
export { default as IconDown} from './IconDown'
export { default as IconEllipsis } from './IconEllipsis'
export { default as IconInfo } from './IconInfo'
export { default as IconPerson } from './IconPerson'
export { default as IconPlus } from './IconPlus'
export { default as IconQuestion } from './IconQuestion'
export { default as IconSearch } from './IconSearch'
export { default as IconThickCross} from './IconThickCross'
export { default as IconUp } from './IconUp'
